### ISSUE TITLE
Plugin doesn't show diffs IDEA version 2020.1 and above

### ISSUE THREAD

**Issue by rusch36** [nhat-phan/merge-request-integration#48]
When user starts review and tries to open a file from this review to see changes, only "Error: can't show diff" appears in the window.

IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.121, built on April 8, 2020

Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 4012M
Cores: 12
Non-Bundled Plugins: net.ntworld.nhat-phan.merge-request-integration-ee, JBehaveBddPlugin, Jetbrains TeamCity Plugin, org.bigtesting.jbehave.buddy, jbehave-syntax-support

IDE log show these fatal errors:

(1)
java.lang.Throwable: Assert: must be called on EDT
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:146)
	at com.intellij.util.ui.EDT.assertIsEdt(EDT.java:30)
	at com.intellij.ui.tabs.impl.JBTabsImpl.getTabs(JBTabsImpl.java:1536)
	at com.intellij.ui.tabs.impl.JBTabsImpl.getTabCount(JBTabsImpl.java:2005)
	at com.intellij.ui.tabs.impl.singleRow.SingleRowPassInfo.<init>(SingleRowPassInfo.java:39)
	at com.intellij.ui.tabs.impl.singleRow.SingleRowLayout.layoutSingleRow(SingleRowLayout.java:101)
	at com.intellij.ui.tabs.impl.JBTabsImpl.doLayout(JBTabsImpl.java:1664)
	at java.desktop/java.awt.Container.validateTree(Container.java:1722)
	at java.desktop/java.awt.Container.validate(Container.java:1657)
	at com.intellij.ui.tabs.impl.JBTabsImpl.revalidateAndRepaint(JBTabsImpl.java:1398)
	at com.intellij.ui.tabs.impl.JBTabsImpl.revalidateAndRepaint(JBTabsImpl.java:1381)
	at com.intellij.ui.tabs.impl.JBTabsImpl.updateText(JBTabsImpl.java:1430)
	at com.intellij.ui.tabs.impl.JBTabsImpl.propertyChange(JBTabsImpl.java:1285)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
	at com.intellij.ui.tabs.TabInfo.append(TabInfo.java:148)
	at com.intellij.ui.tabs.TabInfo.setText(TabInfo.java:118)
	at net.ntworld.mergeRequestIntegrationIde.ui.mergeRequest.MergeRequestDetails$myGetCommitsListener$1.dataReceived(MergeRequestDetails.kt:119)
	at net.ntworld.mergeRequestIntegrationIde.task.GetCommitsTask.run(GetCommitsTask.kt:38)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:930)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:432)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$null$3(ProgressRunner.java:233)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:233)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

(2)
java.lang.NoSuchMethodError: 'void com.intellij.openapi.editor.impl.EditorEmbeddedComponentManager$Properties.<init>(com.intellij.openapi.editor.impl.EditorEmbeddedComponentManager$ResizePolicy, boolean, boolean, int, int)'
	at net.ntworld.mergeRequestIntegrationIde.diff.thread.ThreadViewImpl.initialize(ThreadViewImpl.kt:159)
	at net.ntworld.mergeRequestIntegrationIde.diff.thread.ThreadPresenterImpl.<init>(ThreadPresenterImpl.kt:38)
	at net.ntworld.mergeRequestIntegrationIde.diff.thread.ThreadFactory.makePresenter(ThreadFactory.kt:27)
	at net.ntworld.mergeRequestIntegrationIde.diff.AbstractDiffView.findThreadModelOnLine(AbstractDiffView.kt:232)
	at net.ntworld.mergeRequestIntegrationIde.diff.AbstractDiffView.toggleCommentsOnLine(AbstractDiffView.kt:138)
	at net.ntworld.mergeRequestIntegrationIde.diff.TwoSideTextDiffView.changeCommentsVisibilityOnLine(TwoSideTextDiffView.kt:123)
	at net.ntworld.mergeRequestIntegrationIde.diff.DiffPresenterImpl.onGutterActionPerformed(DiffPresenterImpl.kt:116)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:127)
	at com.intellij.util.EventDispatcher.access$000(EventDispatcher.java:21)
	at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:85)
	at com.sun.proxy.$Proxy259.onGutterActionPerformed(Unknown Source)
	at net.ntworld.mergeRequestIntegrationIde.diff.AbstractDiffView.changeAllCommentsVisibility(AbstractDiffView.kt:199)
	at net.ntworld.mergeRequestIntegrationIde.diff.AbstractDiffView.showAllComments(AbstractDiffView.kt:82)
	at net.ntworld.mergeRequestIntegrationIde.diff.DiffPresenterImpl.onAfterRediff(DiffPresenterImpl.kt:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:127)
	at com.intellij.util.EventDispatcher.access$000(EventDispatcher.java:21)
	at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:85)
	at com.sun.proxy.$Proxy259.onAfterRediff(Unknown Source)
	at net.ntworld.mergeRequestIntegrationIde.diff.AbstractDiffView$diffViewerListener$1.onAfterRediff(AbstractDiffView.kt:32)
	at com.intellij.diff.tools.util.base.DiffViewerBase.fireEvent(DiffViewerBase.java:273)
	at com.intellij.diff.tools.util.base.DiffViewerBase.lambda$null$1(DiffViewerBase.java:146)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.finish(BackgroundTaskUtil.java:110)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.executeAndTryWait(BackgroundTaskUtil.java:98)
	at com.intellij.diff.util.DiffTaskQueue.executeAndTryWait(DiffTaskQueue.java:47)
	at com.intellij.diff.tools.util.base.DiffViewerBase.rediff(DiffViewerBase.java:140)
	at com.intellij.diff.tools.util.base.DiffViewerBase.init(DiffViewerBase.java:78)
	at com.intellij.diff.impl.DiffRequestProcessor$DefaultState.init(DiffRequestProcessor.java:1227)
	at com.intellij.diff.impl.DiffRequestProcessor.lambda$null$1(DiffRequestProcessor.java:343)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:186)
	at com.intellij.diff.impl.DiffRequestProcessor.lambda$doApplyRequest$2(DiffRequestProcessor.java:339)
	at com.intellij.diff.util.DiffUtil.runPreservingFocus(DiffUtil.java:756)
	at com.intellij.diff.impl.DiffRequestProcessor.doApplyRequest(DiffRequestProcessor.java:325)
	at com.intellij.diff.impl.DiffRequestProcessor.lambda$applyRequest$0(DiffRequestProcessor.java:307)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$doWhenFocusSettlesDown$3(FocusManagerImpl.java:180)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2319)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:188)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:140)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:171)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:177)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:41)
	at com.intellij.diff.impl.DiffRequestProcessor.applyRequest(DiffRequestProcessor.java:315)
	at com.intellij.diff.impl.DiffRequestProcessor.applyRequest(DiffRequestProcessor.java:294)
	at com.intellij.diff.impl.CacheDiffRequestProcessor.lambda$null$0(CacheDiffRequestProcessor.java:115)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.finish(BackgroundTaskUtil.java:110)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$null$1(BackgroundTaskUtil.java:90)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:739)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

(3)
java.lang.ClassCastException: class com.intellij.openapi.editor.impl.LineNumberConverterAdapter cannot be cast to class gnu.trove.TIntFunction (com.intellij.openapi.editor.impl.LineNumberConverterAdapter and gnu.trove.TIntFunction are in unnamed module of loader com.intellij.util.lang.UrlClassLoader @7f9a81e8)
	at net.ntworld.mergeRequestIntegrationIde.diff.UnifiedDiffView$myLeftLineNumberConverter$2.invoke(UnifiedDiffView.kt:28)
	at net.ntworld.mergeRequestIntegrationIde.diff.UnifiedDiffView$myLeftLineNumberConverter$2.invoke(UnifiedDiffView.kt:15)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at net.ntworld.mergeRequestIntegrationIde.diff.UnifiedDiffView.getMyLeftLineNumberConverter(UnifiedDiffView.kt)
	at net.ntworld.mergeRequestIntegrationIde.diff.UnifiedDiffView.createGutterIcons(UnifiedDiffView.kt:51)
	at net.ntworld.mergeRequestIntegrationIde.diff.DiffPresenterImpl.onAfterRediff(DiffPresenterImpl.kt:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:127)
	at com.intellij.util.EventDispatcher.access$000(EventDispatcher.java:21)
	at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:85)
	at com.sun.proxy.$Proxy259.onAfterRediff(Unknown Source)
	at net.ntworld.mergeRequestIntegrationIde.diff.AbstractDiffView$diffViewerListener$1.onAfterRediff(AbstractDiffView.kt:32)
	at com.intellij.diff.tools.util.base.DiffViewerBase.fireEvent(DiffViewerBase.java:273)
	at com.intellij.diff.tools.util.base.DiffViewerBase.lambda$null$1(DiffViewerBase.java:146)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.finish(BackgroundTaskUtil.java:110)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.executeAndTryWait(BackgroundTaskUtil.java:98)
	at com.intellij.diff.util.DiffTaskQueue.executeAndTryWait(DiffTaskQueue.java:47)
	at com.intellij.diff.tools.util.base.DiffViewerBase.rediff(DiffViewerBase.java:140)
	at com.intellij.diff.tools.util.base.DiffViewerBase.init(DiffViewerBase.java:78)
	at com.intellij.diff.impl.DiffRequestProcessor$DefaultState.init(DiffRequestProcessor.java:1227)
	at com.intellij.diff.impl.DiffRequestProcessor.lambda$null$1(DiffRequestProcessor.java:343)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:186)
	at com.intellij.diff.impl.DiffRequestProcessor.lambda$doApplyRequest$2(DiffRequestProcessor.java:339)
	at com.intellij.diff.util.DiffUtil.runPreservingFocus(DiffUtil.java:756)
	at com.intellij.diff.impl.DiffRequestProcessor.doApplyRequest(DiffRequestProcessor.java:325)
	at com.intellij.diff.impl.DiffRequestProcessor.lambda$applyRequest$0(DiffRequestProcessor.java:307)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$doWhenFocusSettlesDown$3(FocusManagerImpl.java:180)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2319)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:188)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:140)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:171)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:177)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:41)
	at com.intellij.diff.impl.DiffRequestProcessor.applyRequest(DiffRequestProcessor.java:315)
	at com.intellij.diff.impl.DiffRequestProcessor.applyRequest(DiffRequestProcessor.java:294)
	at com.intellij.diff.impl.CacheDiffRequestProcessor.lambda$null$0(CacheDiffRequestProcessor.java:115)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.finish(BackgroundTaskUtil.java:110)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.executeAndTryWait(BackgroundTaskUtil.java:98)
	at com.intellij.diff.util.DiffTaskQueue.executeAndTryWait(DiffTaskQueue.java:47)
	at com.intellij.diff.util.DiffTaskQueue.executeAndTryWait(DiffTaskQueue.java:38)
	at com.intellij.diff.impl.CacheDiffRequestProcessor.updateRequest(CacheDiffRequestProcessor.java:110)
	at com.intellij.diff.impl.CacheDiffRequestProcessor.updateRequest(CacheDiffRequestProcessor.java:89)
	at com.intellij.diff.impl.DiffRequestProcessor.updateRequest(DiffRequestProcessor.java:185)
	at com.intellij.diff.impl.DiffRequestProcessor.updateRequest(DiffRequestProcessor.java:180)
	at com.intellij.openapi.vcs.changes.ChangeViewDiffRequestProcessor.setCurrentChange(ChangeViewDiffRequestProcessor.java:178)
	at com.intellij.openapi.vcs.changes.ChangeViewDiffRequestProcessor.refresh(ChangeViewDiffRequestProcessor.java:163)
	at com.intellij.openapi.vcs.changes.PreviewDiffSplitterComponent.updatePreview(PreviewDiffSplitterComponent.kt:19)
	at com.intellij.openapi.vcs.changes.ChangesViewManager$ChangesViewToolWindowPanel.lambda$null$13(ChangesViewManager.java:714)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:739)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by bironran** [comment]
same. Plugin version 2020.1.2

IntelliJ version:
IntelliJ IDEA 2020.1 (Community Edition)
Build #IC-201.6668.121, built on April 8, 2020
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-96-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1502M
Cores: 4
Registry: analyze.exceptions.on.the.fly=true
Non-Bundled Plugins: Key Promoter X, com.dmarcotte.handlebars, ASM Bytecode Viewer, ExceptionCatcher, net.ntworld.nhat-phan.merge-request-integration-ce, Lombook Plugin, RegexPlugin, YourKit Java Profiler 2017.02-b66 Integration, com.github.ArtsiomCh.JDCleanRead, online.devliving.stepbuilder.generator, org.dpytel.intellij.plugin.maventest, com.jetbrains.plugins.ini4idea, ideanginx9, PythonCore
Current Desktop: Unity

**Comment by nhat-phan** [comment]
Thank you for using the plugin.

Based on the log, I guess you are using v2020.1.2 which is not compatible with IDEs version 2020.1.*

Please ensure that the plugin version v2020.1.4eap is installed. If you cannot see version v2020.1.4eap in IDE's preference, you can go to [plugin page](https://plugins.jetbrains.com/plugin/13615-merge-request-integration-ee--code-review-for-gitlab/versions), select channel EAP, download and drag the plugin to your IDE manually.

![Screen Shot 2020-04-14 at 11 46 43](https://user-images.githubusercontent.com/34987391/79210791-a6881200-7e45-11ea-8de2-fed4fce57cdb.png)

**Comment by panther-hq** [comment]
Hi, I have the same bugs with the IDE version 2020.1
so i tried the 2020.1.4eap version
and i have new bugs 
```java
com.intellij.diagnostic.PluginException: While loading class net.ntworld.mergeRequestIntegrationIdeEE.MainToolWindowFactory: net/ntworld/mergeRequestIntegrationIde/ui/MainToolWindowFactoryBase [Plugin: net.ntworld.nhat-phan.merge-request-integration-ee] [Plugin: net.ntworld.nhat-phan.merge-request-integration-ee]
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateExtensionWithPicoContainerOnlyIfNeeded(ComponentManagerImpl.kt:663)
	at com.intellij.openapi.wm.ToolWindowEP.getToolWindowFactory(ToolWindowEP.java:115)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$$special$$inlined$processDescriptors$2.accept(ToolWindowManagerImpl.kt:2036)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$$special$$inlined$processDescriptors$2.accept(ToolWindowManagerImpl.kt)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:285)
	at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:155)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.<init>(ToolWindowManagerImpl.kt:2079)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:53)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:645)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:54)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:41)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:115)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:69)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:62)
	at com.intellij.serviceContainer.ComponentManagerImpl$preloadServices$future$1.run(ComponentManagerImpl.kt:787)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:193)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.intellij.diagnostic.PluginException: While loading class net.ntworld.mergeRequestIntegrationIdeEE.MainToolWindowFactory: net/ntworld/mergeRequestIntegrationIde/ui/MainToolWindowFactoryBase [Plugin: net.ntworld.nhat-phan.merge-request-integration-ee]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:262)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:205)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:113)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateExtensionWithPicoContainerOnlyIfNeeded(ComponentManagerImpl.kt:660)
	... 26 more
Caused by: java.lang.NoClassDefFoundError: net/ntworld/mergeRequestIntegrationIde/ui/MainToolWindowFactoryBase
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:877)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:380)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:376)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:340)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:259)
	... 32 more
Caused by: java.lang.ClassNotFoundException: net.ntworld.mergeRequestIntegrationIde.ui.MainToolWindowFactoryBase PluginClassLoader[net.ntworld.nhat-phan.merge-request-integration-ee, 2020.1.4eap] com.intellij.ide.plugins.cl.PluginClassLoader@59c77b99
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:115)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 39 more

**Comment by nhat-phan** [comment]
@panther-hq I guess your problem happens when you have EE & CE installed at the same time. Could you please verify the problem and try to use only 1 edition?

**Comment by panther-hq** [comment]
@nhat-phan Previously I had CE and EE installed, but after the stable version of EE does not work with version 2020.1 I uninstalled everything and installed only EE EAP

![image](https://user-images.githubusercontent.com/8721698/79493314-9a58ac00-8021-11ea-895b-808857492fd0.png)

![image](https://user-images.githubusercontent.com/8721698/79493405-bc522e80-8021-11ea-893f-0d6aca0793b9.png)

**Comment by nhat-phan** [comment]
@panther-hq thank for the stack traces, I'll investigate and fix the problem. Sorry for the inconvenient :(

**Comment by panther-hq** [comment]
@nhat-phan with version 2020.1.5-built-for-ide-2020. it's works
Thanks
